# Numpy Library

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Datatypes

dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)
dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

In [3]:
arr = np.array([1,2,3], dtype='f4')
arr
print(arr.dtype)

float32


In [4]:
#Create an array
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#create an evenly spaced array
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
#create an array evenly spaced in specified interval
arr = np.linspace(0,10,25)
arr

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [7]:
#create the array of random values
arr = np.random.rand(3,3)
arr

array([[0.78219908, 0.87953446, 0.11850086],
       [0.88495848, 0.8263806 , 0.21830464],
       [0.67545699, 0.68943854, 0.47023393]])

In [8]:
#create an array of zeros
zeros = np.zeros((2,3), dtype='i4')
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
#create an array of ones
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
empty = np.empty_like(arr)
empty

array([[0.78219908, 0.87953446, 0.11850086],
       [0.88495848, 0.8263806 , 0.21830464],
       [0.67545699, 0.68943854, 0.47023393]])

In [11]:
#Create an array with constant value
a1 = np.full((2,3), 5)
a1


array([[5, 5, 5],
       [5, 5, 5]])

In [12]:
#create an array using repetation
arr = [0,1,2]
np.repeat(arr,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [13]:
#Create identity matrix
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
#Create 2D matrix
arr = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [15]:
np.info(arr)

class:  ndarray
shape:  (4, 3)
strides:  (12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2bd27871180
byteorder:  little
byteswap:  False
type: int32


In [ ]:
#Sampling method
#Set seed
a1 = np.random.seed(123)
a1

In [ ]:
# set random independent state 
rs = np.random.RandomState(321)
rs.rand(10)

In [ ]:
# Genrate a random sample frominterval [0,1] 
np.random.rand()

In [ ]:
#1-D
np.random.rand(3)

In [ ]:
#2-D
np.random.rand(3,3)

In [ ]:
np.random.randint(1,10,2, dtype='i8')

In [ ]:
#create float random values
np.random.rand(10)

In [ ]:
np.random.ranf(10)

In [ ]:
#Create 2-D array
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[4,7,6]])
arr

In [ ]:
np.info(arr)

In [ ]:
arr.dtype

In [ ]:
arr.shape

In [ ]:
len(arr)

In [ ]:
arr/10

In [ ]:
arr/0

In [ ]:
#Exponential value
np.exp(arr)

In [ ]:
np.log(arr)

In [ ]:
np.log10(arr)

In [ ]:
np.log2(arr)

In [ ]:
np.sqrt(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.cos(arr)

In [ ]:
np.sum(arr)

In [ ]:
np.sum(arr, axis=0)#Row-wise sum

In [ ]:
np.sum(arr, axis=1)#Column wise sum

In [ ]:
np.max(arr)

In [ ]:
np.max(arr, axis = 0)

In [ ]:
np.max(arr, axis = 1)

In [ ]:
#Sort an array
arr = np.random.rand(5,5)
arr

In [ ]:
np.sort(arr, axis=0)

In [ ]:
np.sort(arr, axis=1)

In [ ]:
np.transpose(arr)

In [ ]:
#Flatterning an array
arr.flatten()

In [ ]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
#Method 1
arr1.dot(arr2)

In [ ]:
#Method 2
np.dot(arr1,arr2)

In [ ]:
#Method 3
arr1 @ arr2

In [ ]:
#Eigen values
arr = np.random.rand(5,5)
arr

In [ ]:
w, v = np.linalg.eig(arr)

In [ ]:
print(w)
print(v)

In [ ]:
np.linalg.det(arr)

In [ ]:
np.linalg.inv(arr)

In [ ]:
#Linear Equation
y = [1,2,3,4,5]
solution, residual, rank, singular = np.linalg.lstsq(arr,y)


In [ ]:
print(solution)

In [ ]:
print(residual)

In [ ]:
print(rank)

In [ ]:
print(singular)

# Pandas Library

In [17]:
import pandas as pd

In [18]:
data1 = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}

In [19]:
df = pd.DataFrame(data1)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [20]:
df.head()

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [21]:
df.tail()

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [22]:
df[1:3]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [58]:
df[1:-3]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [ ]:
df.columns

In [26]:
df['day']

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [ ]:
df[['day','temperature']]

In [ ]:
#Calculate the maximum temperature in the day
df['temperature'].max()

In [ ]:
#Calculate the temperature greater that 31 
df[df['temperature']>31]

In [59]:
#Calculate the day in which temperature is 32
df[df['temperature']==32]

day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain

In [60]:
#Calculate the event on which temparature was minimum.
df[df['temperature']==df['temperature'].min()]

day  temperature  windspeed event
3  1/4/2017           24          7  Snow

In [27]:
#Setting an index
df.set_index('day', inplace=True)

In [28]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day')

In [29]:
df.loc['1/1/2017']

temperature      32
windspeed         6
event          Rain
Name: 1/1/2017, dtype: object

In [30]:
df.reset_index(inplace=True)
df.head()

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [31]:
df.set_index('event',inplace=True)
df


day  temperature  windspeed
event                                  
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [32]:
df.loc['Sunny']

day  temperature  windspeed
event                                  
Sunny  1/2/2017           35          7
Sunny  1/6/2017           31          2

In [33]:
#Example: Read CSV file
import pandas as pd

In [35]:
df = pd.read_csv("D:/Test/Day11.csv")
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [36]:
#HW: Convert dictionary, Tuple and list data into Dataframe

In [61]:
#Reading Excel file
df=pd.read_excel("Day12.xlsx","Sheet1")
df

day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [63]:
#Reading Dictionary
import pandas as pd
data2 = {
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain', 'Sunny', 'Snow']
}
df = pd.DataFrame(data2)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [64]:
#Reading tuples
data3 = [
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
df = pd.DataFrame(data=data3, columns=['day','temperature','windspeed','event'])
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [65]:
#Reading Multiple dictionaries
data4 = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
    
]
df = pd.DataFrame(data=data4, columns=['day','temperature','windspeed','event'])
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [ ]:
HW: Design an Student Result Analysis Application

# Series data structure

In [40]:
obj = pd.Series([1,"Anish", 3.5, "Niraj"])
obj

0        1
1    Anish
2      3.5
3    Niraj
dtype: object

In [41]:
obj[1]

'Anish'

In [42]:
obj.values

array([1, 'Anish', 3.5, 'Niraj'], dtype=object)

In [45]:
obj1 = pd.Series([1,"Anish", 3.5, "Niraj"], index=["a","b","c","d"])
obj1

a        1
b    Anish
c      3.5
d    Niraj
dtype: object

In [47]:
obj1["b"]

'Anish'

In [49]:
#Example:
Marks = {"Nayan":90,"Prajwal":89,"Saket":75,"Ranjeet":78,"Mayur":98}
Result = pd.Series(Marks)
Result

Nayan      90
Prajwal    89
Saket      75
Ranjeet    78
Mayur      98
dtype: int64

In [50]:
#Print the marks for Ranjeet
Result["Ranjeet"]

78

In [51]:
#Print the marks > 80
Result[Result>80]

Nayan      90
Prajwal    89
Mayur      98
dtype: int64

In [52]:
#Assign Mayur = 60 marks
Result["Mayur"]=60

In [53]:
Result

Nayan      90
Prajwal    89
Saket      75
Ranjeet    78
Mayur      60
dtype: int64